apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalogs
data:
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive-service:9083
  delta.properties: |
    connector.name=delta-lake
    delta.storage.root=/tmp/delta
