apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalogs
data:
  delta.properties: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive-service:9083
    delta.register-table-procedure.enabled=true
