apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino
        image: trinodb/trino:432
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: delta-storage
          mountPath: /tmp/delta
        - name: trino-catalogs
          mountPath: /etc/trino/catalog
      volumes:
      - name: delta-storage
        persistentVolumeClaim:
          claimName: delta-pvc
      - name: trino-catalogs
        configMap:
          name: trino-catalogs
---
apiVersion: v1
kind: Service
metadata:
  name: trino-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: trino
