apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      containers:
      - name: hive
        image: apache/hive:3.1.3
        env:
          - name: SERVICE_NAME
            value: "metastore"
          - name: HIVE_CONF_DIR
            value: "/opt/hive/conf"
          - name: HIVE_OPTS
            value: "hive.metastore.warehouse.dir=/tmp/delta"
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: delta-storage
          mountPath: /tmp/delta
      volumes:
      - name: delta-storage
        persistentVolumeClaim:
          claimName: delta-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hive-service
spec:
  type: ClusterIP
  ports:
  - port: 9083
    targetPort: 9083
    protocol: TCP
  selector:
    app: hive
