apiVersion: v1
kind: PersistentVolume
metadata:
  name: delta-pv
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/spark
