apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delta-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: manual
