apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-aggregate
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "spark-jobs:latest"
  imagePullPolicy: Never
  mainApplicationFile: local:///opt/spark/jobs/aggregate.py
  sparkVersion: "3.4.0"
  deps:
    packages:
      - "io.delta:delta-core_2.12:2.4.0"
      - org.apache.spark:spark-streaming-kafka-0-10_2.12:3.4.0
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0
  sparkConf:
    spark.kubernetes.file.upload.path: /opt/spark
    spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: delta-pvc
        readOnly: false
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: volume
        mountPath: /tmp/delta
    envFrom:
      - configMapRef:
          name: env-config
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: volume
        mountPath: /tmp/delta
    envFrom:
      - configMapRef:
          name: env-config
