apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-job
spec:
  template:
    spec:
      containers:
      - name: producer
        image: my-producer-image
        envFrom:
        - configMapRef:
            name: kafka-config
      restartPolicy: Never
  backoffLimit: 3